= Getting Started: For Developers of Tangential Libs

This project is a set of libraries created using `ng generate library <name>`. See the angular docs at https://angular.io/guide/creating-libraries[].

== Clone the repository, install all the things:
[source, bash]
git clone
cd tangential-libs
npm install

The project contains https://www.jetbrains.com/webstorm/[WebStorm] project files. Once it has been cloned you can open the project in WebStorm (or Intellij).

== Build the libraries

The demonstration application code references the 'dist/' output directory to consume the libraries. With a fresh clone of the repository, you'll see errors on any `import x from @tangential/foo`.

[source, bash]
npx gulp buildLibsDevelopment

This command is just running `npx ng build <libName> --configuration development` on each of the libraries.


=== Run with watch enabled

When developing against a particular library, you'll want to run a watch build in a second or background shell:

For example, if you're working on the `core`  library:

[source, bash]
npx ng build @tangential/core --configuration development --watch


=== Run tests

Similar to build, just target the library with the `ng test` command:

[source, bash]
npx ng test @tangential/core


== Global Tools

There are a handful of tools that are usually installed globally included in the devDependencies of the Tangential Demo. Global NPM installs should be discouraged, as avoiding versions mis-matches between different projects is a pain. There's no great reason to use Globals now that the `npx` command makes running locally installed npm tools so easy.

== Firebase Components

@todo: document the 'local development mode' process for Firebase development and testing.


== The Demonstration Application

The primary purpose of the application configured in this project is to visualize the various UI widgets in the `components` and `input-widgets` libraries.

Though not really its intended purpose, this project is also a useful example of how to develop a large application that separates functionality into libraries. Specifically, libraries that won't be published to NPM or another package repository.




=== Running end-to-end tests

Work in progress. Protractor is dead. Long live E2E testing...
