= Tangential Libraries

Live demo available https://tangential-demo.firebaseapp.com/[here].

== Firebase, Analytics, User Management, Advertising...

These Angular libraries provide the client-side functionality for the Tangential framework. Firebase data access, user management, analytics, etc.

See the Tangential project itself for the project description and getting started information.

== Getting Started: Using Tangential widgets in your project

Each component has it's own readme file, which should (eventually) contain the required install steps specific to that component.

If you have not started your project yet we very much recommend using the Angular-CLI to create your project, then follow the docs below.

With that out of the way, let's get stated installing widgets into our new project.

=== Install all the things

Install any of the components you wish to use. Be sure to check the peer dependencies of the components you do install if you chose not to install them all.

Also, consider that at the moment all of the projects are using pre-release tags.

[source, bash]
npm install --save @tangential/admin-console
npm install --save @tangential/analytics
npm install --save @tangential/authorization-service
npm install --save @tangential/components
npm install --save @tangential/configurable-widgets
npm install --save @tangential/core
npm install --save @tangential/firebase-util
npm install --save @tangential/input-widgets
npm install --save @tangential/media-types
npm install --save @tangential/visitor-service


All components require Angular 13+. Some also require firebase. Do take a look at this project's link:./package.json file for the most up to date list of dependencies, or at each package's package.json file for the peer dependencies specific to the package.

== Graduation

We will be moving libraries out of this general bucket-o'-libs git repository and into their own projects/repositories over time, as they mature. For the time being it is useful to develop them all as a cohesive whole, as we settle on design patterns. Changing one project is much easier than trying to propagate those changes across many smaller projects.




